# Generated by Django 5.2.5 on 2026-02-24 22:55

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_orders_user',
            old_name='orders_user_id_4e08b8_idx',
        ),
        migrations.RenameIndex(
            model_name='orderdetail',
            new_name='idx_order_details_order',
            old_name='order_detai_order_i_4e3e53_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='idx_products_category',
            old_name='products_categor_4083ff_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='idx_products_brand',
            old_name='products_brand_b2547a_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='idx_product_images_product',
            old_name='product_ima_product_55415d_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='idx_product_images_variant',
            old_name='product_ima_variant_3b8a6a_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='idx_product_images_primary',
            old_name='idx_images_primary',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='idx_reviews_product',
            old_name='reviews_product_3516b2_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='idx_reviews_user',
            old_name='reviews_user_id_79db63_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='idx_reviews_rating',
            old_name='reviews_rating_17e8a4_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Количество товара в корзине (минимум 1)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Скидка в процентах (0–100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='idx_carts_user'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='idx_cart_items_cart'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product_size'], name='idx_cart_items_product_size'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='idx_favorites_user'),
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['variant'], name='idx_product_sizes_variant'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='idx_product_variants_product'),
        ),
    ]
