# Generated by Django 5.2.5 on 2026-03-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_orders_user_id_4e08b8_idx_idx_orders_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
