# Generated by Django 5.2.5 on 2026-03-11 17:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
