# Generated by Django 5.2.5 on 2026-03-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimage_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=None, upload_to='products/'),
            preserve_default=False,
        ),
    ]
