# Generated by Django 5.2.5 on 2026-03-17 11:34

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_productimage_image_path_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
