from django.urls import path

from .views import (
    account_state,
    admin_catalog_options,
    admin_order_detail_manage,
    admin_orders,
    admin_product_detail_manage,
    admin_products,
    admin_sales_report,
    admin_user_detail_manage,
    admin_users,
    bestseller_list,
    create_order,
    current_user,
    login_user,
    logout_user,
    confirm_password_reset,
    product_detail,
    product_reviews,
    product_filters,
    product_list,
    register_user,
    request_password_reset,
    search_by_image,
    sync_account_state,
)

urlpatterns = [
    path("auth/register/", register_user),
    path("auth/login/", login_user),
    path("auth/me/", current_user),
    path("auth/logout/", logout_user),
    path("auth/password-reset/request/", request_password_reset),
    path("auth/password-reset/confirm/", confirm_password_reset),
    path("admin/catalog/options/", admin_catalog_options),
    path("admin/products/", admin_products),
    path("admin/products/<int:product_id>/", admin_product_detail_manage),
    path("admin/orders/", admin_orders),
    path("admin/orders/<int:order_id>/", admin_order_detail_manage),
    path("admin/reports/sales/", admin_sales_report),
    path("admin/users/", admin_users),
    path("admin/users/<int:user_id>/", admin_user_detail_manage),
    path("account/state/", account_state),
    path("account/sync/", sync_account_state),
    path("orders/", create_order),
    path("products/filters/", product_filters),
    path("products/", product_list),
    path("products/bestsellers/", bestseller_list),
    path("products/<int:product_id>/", product_detail),
    path("products/<int:product_id>/reviews/", product_reviews),
    path("search-by-image/", search_by_image),
]
